# This workflow generates response time graphs
name: Graphs CI

on:
  schedule:
    # Run daily at midnight
    - cron: "0 0 * * *"
  repository_dispatch:
    types: [graphs]
  workflow_dispatch:

jobs:
  release:
    name: Generate graphs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Generate graphs
        run: |
          export UPPTIME_RC=.upptimerc.prod.yml
          pnpx @upptime/uptime-monitor graphs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}