# This workflow generates response time graphs
name: Graphs CI

on:
  schedule:
    # Run daily at midnight
    - cron: "0 0 * * *"
  repository_dispatch:
    types: [graphs]
  workflow_dispatch:

jobs:
  release:
    name: Generate graphs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
          
      - name: Generate graphs
        uses: upptime/uptime-monitor@v1.40.1
        with:
          command: "graphs"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          UPPTIME_RC: .upptimerc.prod.yml