# This workflow builds and deploys the status page
name: Static Site CI

on:
  schedule:
    # Run daily at 1 AM
    - cron: "0 1 * * *"
  repository_dispatch:
    types: [static_site]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  release:
    name: Build and deploy site
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
          
      - name: Generate site
        uses: upptime/uptime-monitor@v1.40.1
        with:
          command: "site"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          UPPTIME_RC: .upptimerc.prod.yml
          
      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site/status-page/__sapper__/export/
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4