# This workflow generates the summary data for the status page
name: Summary CI

on:
  schedule:
    # Run daily
    - cron: "0 0 * * *"
  repository_dispatch:
    types: [summary]
  workflow_dispatch:

jobs:
  release:
    name: Generate Summary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
          
      - name: Update summary in README
        uses: upptime/uptime-monitor@v1.40.1
        with:
          command: "readme"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          UPPTIME_RC: .upptimerc.prod.yml
          
      - name: Generate summary
        uses: upptime/uptime-monitor@v1.40.1
        with:
          command: "summary"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          UPPTIME_RC: .upptimerc.prod.yml