# This workflow runs the Upptime monitor for production endpoints only
name: Uptime CI

on:
  schedule:
    # Run every 5 minutes
    - cron: "*/5 * * * *"
  repository_dispatch:
    types: [uptime]
  workflow_dispatch:

jobs:
  release:
    name: Check status
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
          
      - name: Check endpoint status
        uses: upptime/uptime-monitor@v1.40.1
        with:
          command: "update"
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPPTIME_RC: .upptimerc.prod.yml
          HEALTH_API_KEY: ${{ secrets.HEALTH_API_KEY }}